apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: postgres-backup
            image: ghcr.io/beatlang/postgres-backup:next
            imagePullPolicy: Always
            env:
            - name: PGHOST
              value: postgres-service
            - name: PGPORT
              value: "4532"
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: backup-secret
                  key: backup_db_name_1
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: backup-secret
                  key: backup_db_username_1
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-secret
                  key: backup_db_password_1
            - name: AZ_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: backup-secret
                  key: backup_storage_account
            - name: AZ_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: backup-secret
                  key: backup_container
            - name: AZ_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secret
                  key: backup_account_key
