kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
allowVolumeExpansion: true